---
- hosts: rhel
  tasks:
  - name: Wait for port 8000 to become open on the host, don't start checking for 10 seconds
    wait_for:
      port: 22
      delay: 10
      #connect_timeout: 1
      timeout: 30
      #delegate_to: localhost
    register: output

  - debug:
          msg: "{{ output }}"    
